version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fit-db
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - JWT_SECRET=supersecretjwt
      - BOOTSTRAP_KEY=bootstrap-secret-key
      - COACH_SERVICE_URL=http://coach:5002/wod
    depends_on:
      db:
        condition: service_healthy
      coach:
        condition: service_started
    networks:
      - fit

  coach:
    build:
      context: .  # FIXED: point to project root
      dockerfile: src/coach/Dockerfile.coach  # Point to the coach-specific Dockerfile
    ports:
      - "5002:5002"
    networks:
      - fit

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=fit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fit-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

networks:
  fit:
