version: "3.7"

services:
  monolith:
    build:
      context: .
      dockerfile: monolith.Dockerfile
    ports:
      - "12101:5000"
    volumes:
      - ./src/fit:/app/src/fit
    links:
      - monolith-db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:docker@monolith-db:5432/fit-db
      - FIT_API_KEY=some_very_secret_key
      - COACH_URL=http://coach:5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=docker
    networks:
      - fit
    depends_on:
      rabbitmq:
        condition: service_healthy
      monolith-db:
        condition: service_healthy

  coach:
    build:
      context: .
      dockerfile: coach.Dockerfile
    ports:
      - "12102:5000"
    volumes:
      - ./src/coach:/app/src/coach
    links:
      - coach-db
      - rabbitmq
    environment:
      - MONOLITH_URL=http://monolith:5000
      - FIT_API_KEY=some_very_secret_key
      - DATABASE_URL=postgresql://postgres:docker@coach-db:5432/coach-db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=docker
    networks:
      - fit
    depends_on:
      rabbitmq:
        condition: service_healthy

  monolith-db:
    image: postgres:latest
    ports:
      - "12100:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=fit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fit-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

  coach-db:
    image: postgres:latest
    ports:
      - "12103:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=coach-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "coach-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

  rabbitmq:
    user: rabbitmq
    image: rabbitmq:3.12.10-management
    ports:
      - "12104:5672"
      - "12105:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=docker
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 60s
      retries: 5
    networks:
      - fit

  stats:
    build:
      context: .
      dockerfile: stats.Dockerfile
    ports:
      - "12106:5002"
    volumes:
      - ./src/stats:/app/src/stats
      - ./main_stats.py:/app/main_stats.py
    depends_on:
      stats-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:docker@stats-db:5432/stats-db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=docker
    networks:
      - fit

  stats-db:
    image: postgres:latest
    ports:
      - "12107:5433"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "stats-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

  billing:
    build:
      context: .
      dockerfile: billing.Dockerfile
    ports:
      - "12108:5000"
    volumes:
      - ./src/billing:/app/src/billing
      - ./main_billing.py:/app/main_billing.py
    environment:
      - DATABASE_URL=postgresql://postgres:docker@billing-db:5432/billing
      - JWT_SECRET=fit-secret-key
      - MONOLITH_URL=http://monolith:5000
    depends_on:
      billing-db:
        condition: service_healthy
    networks:
      - fit

  billing-db:
    image: postgres:latest
    ports:
      - "12109:5434"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=billing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "billing"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit


networks:
  fit:
